### ISSUE TITLE
[Question | Help] Stylua does not use `stylua.toml` configuration to format

### ISSUE THREAD

**Issue by hankertrix** [creativenull/efmls-configs-nvim#145]
I am not using this plugin to configure `efm-language-server`, and I am instead using the `config.yaml` file to configure the language server. However, I copied my configurations from the defaults in this repository, and they work just fine.

For some strange reason, `stylua` called by the `efm-language-server` is not reading the `stylua.toml` or `.stylua.toml` files in my project directories. Here is the `stylua` part of my `config.yaml`:

```yaml
tools:
  lua-stylua: &lua-stylua
    format-command: >
       stylua --color Never \
         ${--range-start:charStart} ${--range-end:charEnd} -
    format-can-range: true
    format-stdin: true
    root-markers:
      - "stylua.toml"
      - ".stylua.toml"
```

I have no idea why this is happening, especially since `prettierd` works just fine and does properly read the `.prettierrc` file.

I am also currently using `stylua` version `v2.0.1`, but I don't think that is an issue, since running `stylua` in the Neovim terminal works just fine, and `null-ls` also works just fine.
